
# 数据库配置信息
HOSTNAME = '118.195.231.62'
PORT = '3306'
DATABASE = 'nmqa'
USERNAME = 'root'
PASSWORD = 'KT2333'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "asdscdcdsja1w231123"

# 邮箱配置
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "1530151243@qq.com"
MAIL_PASSWORD = "ktfucwyhwxphhhhh"
MAIL_DEFAULT_SENDER = "1530151243@qq.com"